version: "3.8"

services:
  web:
    build: ./web
    command: >
      sh -c "/wait-for-it.sh postgres:5432 -- 
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 --workers 3 core.wsgi:application"
    volumes:
      - ./webapp:/code
      - static_volume:/code/static
    env_file:
      - ./web/.env
    depends_on:
      - postgres
    networks:
      - backend

  bot:
    build: ./bot
    env_file:
      - ./bot/.env
    volumes:
      - ./bot:/code
    depends_on:
      - postgres
    networks:
      - backend

  postgres:
    image: postgres:latest
    env_file:
      - ./web/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/code/static
      - ./nginx/ssl:/etc/letsencrypt
    depends_on:
      - web
    networks:
      - backend
  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/ssl:/etc/letsencrypt
      - ./nginx/ssl:/var/lib/letsencrypt
    command: certonly --standalone --non-interactive --agree-tos --email your@email.com -d glasshalf.ru -d www.glasshalf.ru
    depends_on:
      - nginx
    networks:
      - backend

volumes:
  postgres_data:
  static_volume:

networks:
  backend:
    driver: bridge