# Generated by Django 5.2 on 2025-04-19 11:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название должности')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='RegisteredUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=255, unique=True, verbose_name='Telegram ID')),
                ('telegram_username', models.CharField(max_length=255, verbose_name='Telegram Username')),
                ('lucky_username', models.CharField(max_length=255, verbose_name='Lucky Username')),
                ('rest_title', models.CharField(max_length=168, verbose_name='Название ресторана')),
                ('phone', models.CharField(help_text='Введите номер в международном формате, например +1234567890', max_length=16, unique=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{10,15}$', 'Введите корректный международный номер')], verbose_name='Телефонный номер')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('is_subscribed', models.BooleanField(default=False, verbose_name='Подписан на канал')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gamble.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Зарегистрированный пользователь',
                'verbose_name_plural': 'Зарегистрированные пользователи',
            },
        ),
    ]
