# Generated by Django 5.2 on 2025-04-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamble', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registereduser',
            options={'verbose_name': 'Участник', 'verbose_name_plural': 'Участники'},
        ),
        migrations.RemoveField(
            model_name='registereduser',
            name='email',
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='is_subscribed',
            field=models.BooleanField(verbose_name='Подписан на канал'),
        ),
    ]
